<?php include 'header.phtml'; ?>

<main id="biography" class="container">
	<center><img src="images/jim-bio.jpg"></center>

	<h1>Humana Project</h1>

	<div id="text">
		<p>Humana Project voit le jour à Nantes en 2018.
		Une initiative simple : entreprendre et bâtir un projet artistique gravitant autour de la musique, pour y faire parvenir une note de poésie et d’engagement militant.
		Incarnant un personnage à l’allure d’écrivain intemporel, il ajoute une touche de mystère et de fantaisie à son univers nuancé.
		</p>

		<p>La musique électronique souvent ressentie de façon personnelle se voit guidé par un fil conducteur, une histoire, qui prend racine dans des valeurs humanistes et élémentaires.</p>

		<p>Au travers de ce mode de communication il puise ses influences aussi bien en musique classique et traditionnelle, qu’en musique électronique en tout genre. 
		Il s’épanouit dans la musique techno mais n’hésite pas à étendre ses frontières créatives pour donner naissance à de nouvelles réalisations.</p>

		<div style="border-bottom:1px solid black"></div>
		
		<p>Humana Project was born in Nantes in 2018. A simple initiative: to undertake and build an artistic project revolving around music, to send a note of poetry and militant commitment. Embodying the character of a timeless writer, he adds a touch of mystery and fantasy to his nuanced universe.</p>

		<p>Electronic music often felt in a personal way is guided by a thread, a story, which takes root in humanistic and elementary values.</p>

		<p>Through this mode of communication he draws his influences in classical and traditional music as well as in electronic music of all kinds. He blossomed in techno music but did not hesitate to expand his creative boundaries to give birth to new achievements</p>
	</div>

      
</main>