<?php include 'header.phtml'; ?>

<main class="container" id="discography">

		
	<div class="flex">
		<div class="albums">

			<h1>Albums</h1>
			<div>			
				<img class='cover' src="images/Album1.png">
				<p><strong>Tome 1 - Entre rêve et matière</strong> <br> <small>2018</small></p>		
			</div>

		</div>

		<div class="EP">

			<h1>EP</h1>
			<div>			
				<img class='cover' src="images/EP-miniature.jpg">
				<p><strong>Résonance</strong> <br> <small>2020</small></p>		
			</div>

		</div>
	</div>
		
	<div class="flex singles">
		<div style="width: 50%">
			<h1>Singles</h1>
			<p><strong>Swiftness</strong><small>   /  2017</small></p>
			<p> <strong>Earth Moaning</strong><small>   /  2017</small></p>
			<p><strong>Panthera</strong><small>   /  2017</small></p>
			<p><strong>L'oiseau d'argent</strong><small>   /  2017</small></p>
			<p><strong>Glitch Forest</strong><small>   /  2017</small></p>
			<p><strong>Shaya</strong><small>   /  2017</small></p>
			<p><strong>Valse nocturne</strong><small>   /  2017</small></p>
			<p><strong>Kundalini</strong><small>   /  2017</small></p>
			<p><strong>Le Mat</strong><small>   /  2017</small></p>
		</div>
				
		<div>
			<h1>Remix</h1>
			<p><strong>Sub Family Jam - Smoked Stoep( Humana Project remix )</strong> <small>    2018 </small></p>
		</div>
	</div>
		
</main>