<?php include 'header.phtml'; ?>

<main id="medias" class="container">
	<h1>Photos</h1>

		<div id="slider">
        	<img src="images/pic1.JPG" alt="" id="slide">

        	<div id="precedent" onclick="ChangeSlide(-1)"><</div>
        	<div id="suivant" onclick="ChangeSlide(1)">></div>
    	</div>
			

	<h1 style="margin-top: 100px">Videos</h1>
		<div id="video" class="flex">
			<iframe width="560" height="315" src="https://www.youtube.com/embed/n8gZ_A5ptJM" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

			<iframe width="560" height="315" src="https://www.youtube.com/embed/C2EOxHLnEoY" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
		</div>




	</main>
	<script type="text/javascript" src="js/main.js"></script>