<?php include 'header.phtml'; ?>

<main id="partners" class="container">
	<h1>Partners</h1>
	<div class="flex-partner">
		<div class="partner-info flex">
			<p><strong>Thomas Ricou</strong><br>Ingénieur son</p>
		</div>

		<div class="partner-info flex">
			<p><strong>Morgane Delmotte</strong><br>Vidéaste</p>
		</div>

		<div class="partner-info flex">
			<a href="https://www.facebook.com/Janelle-Couture-503531806469342/" target="_blank"><p><strong>Janelle Couture</strong><br>Couturière</p></a>
		</div>

		<div class="partner-info flex">
			<p><strong>Michael Carteron</strong><br>Designer</p>
		</div>

		<div class="partner-info flex">
			<p><strong>Yann Rondeau</strong><br>Développeur web</p>
		</div>

		<div class="partner-info flex">
			<p><strong>Ha Lan Leduc</strong><br>Harpiste</p>
		</div>

		<div class="partner-info flex">
			<a href="https://www.deviantart.com/zeldanet" target="_blank"><p><strong>Morgan Zel</strong><br>Dessinatrice</p></a>
		</div>
	</div>
</main>
